alter table HANDANALYZERC_PLAYER add constraint FK_HANDANALYZERC_PLAYER_ON_GAME foreign key (GAME_ID) references HANDANALYZERC_GAME(ID);
create index IDX_HANDANALYZERC_PLAYER_ON_GAME on HANDANALYZERC_PLAYER (GAME_ID);
