-- begin HANDANALYZERC_PLAYER
alter table HANDANALYZERC_PLAYER add constraint FK_HANDANALYZERC_PLAYER_ON_GAME foreign key (GAME_ID) references HANDANALYZERC_GAME(ID)^
create index IDX_HANDANALYZERC_PLAYER_ON_GAME on HANDANALYZERC_PLAYER (GAME_ID)^
-- end HANDANALYZERC_PLAYER
-- begin HANDANALYZERC_PLAYER_ACTION
alter table HANDANALYZERC_PLAYER_ACTION add constraint FK_HANDANALYZERC_PLAYER_ACTION_ON_PLAYER foreign key (PLAYER_ID) references HANDANALYZERC_PLAYER(ID)^
alter table HANDANALYZERC_PLAYER_ACTION add constraint FK_HANDANALYZERC_PLAYER_ACTION_ON_GAME foreign key (GAME_ID) references HANDANALYZERC_GAME(ID)^
create index IDX_HANDANALYZERC_PLAYER_ACTION_ON_PLAYER on HANDANALYZERC_PLAYER_ACTION (PLAYER_ID)^
create index IDX_HANDANALYZERC_PLAYER_ACTION_ON_GAME on HANDANALYZERC_PLAYER_ACTION (GAME_ID)^
-- end HANDANALYZERC_PLAYER_ACTION
